### ISSUE TITLE
Connections succeeds without credentials

### ISSUE THREAD

**Issue by ParitoshBh** [odwrtw/transmission#8]
Here's what I am using,

```go
	// Simple client
        conf := transmission.Config{
		Address: fmt.Sprintf("http://%s:%s/transmission/rpc", host, "9091"),
		// User: username,
		// Password: password,
	}
	client, err := transmission.New(conf)
	if err != nil {
		log.Println(err)
	}

	// Get all torrents
	torrents, err := client.GetTorrents()
	if err != err {
		log.Println(err)
	}
	log.Println(torrents)
```

I have authentication enabled for transmission and as such connection (should) require username/password. However, if I skip passing credentials, the connection still succeeds when I was hoping for it to fail and throw some sort of error.

Is this behaviour expected?

**Comment by PouuleT** [comment]
Hello!

I tried your code and in my case, GetTorrents() does return an error:
```
&json.SyntaxError{msg:"invalid character '<' looking for beginning of value", Offset:1}
```
That's because we're not checking the http.Status of the rpc responses and that is not the expected behaviour 

I've just made a pull request (https://github.com/odwrtw/transmission/pull/9) checking that we're dealing with a success response before parsing the json, with the patch, we have a better error that we can understand: 
```
&errors.errorString{s:"got http error 401 Unauthorized"}
```

I hope this answer your issue =), thanks for raising it!

**Comment by ParitoshBh** [comment]
It does, appreciate quick turn around!
